#!/bin/sh

. /etc/rc.subr

name=route20
rcvar=route20_enable

command="/root/route20/${name}" # Modify this for where you keep your binary
command_args="/root/route20/${name}.ini" # Modify this for where you keep the configuration

pidfile="/var/run/${name}.pid"
extra_commands=reload

load_rc_config $name
: ${route20_enable:=yes}
run_rc_command "$1"